using Android.App;
using MvvmCross.Droid.Views;

namespace iPantry.UI.Droid.Views
{
    [Activity(Label = "Main Menu")]
    public class MainMenuView : MvxActivity
    {
        protected override void OnViewModelSet()
        {
            // This uses a resource identifier generated by Android to identify the view.
            SetContentView(Resource.Layout.View_MainMenu);
        }
    }
}